sudo: false
language: ruby
cache: bundler
jdk: oraclejdk8
rvm:
  - jruby-1.7.25
env:
  - KAFKA_VERSION=0.9.0.0 
before_install: ./kafka_test_setup.sh
before_script:
  - bundle exec rake vendor
  - bundle exec rake install_jars
script: bundle exec rspec && bundle exec rspec --tag integration
