sudo: false
language: ruby
cache: bundler
rvm:
  - jruby-19mode
before_install:
  - curl -s -o kafka.tgz http://ftp.wayne.edu/apache/kafka/0.9.0.0/kafka_2.11-0.9.0.0.tgz
  - mkdir kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties &
  - kafka/bin/kafka-server-start.sh kafka/config/server.properties &
  - sleep 3
  - kafka/bin/kafka-topics.sh --create --partitions 3 --replication-factor 1 --topic topic3 --zookeeper localhost:2181
  - wget https://s3.amazonaws.com/data.elasticsearch.org/apache_logs/apache_logs.txt
  - cat apache_logs.txt | kafka/bin/kafka-console-producer.sh --topic topic3 --broker-list localhost:9092
before_script:
  - bundle exec rake vendor
  - bundle exec rake install_jars
script: bundle exec rspec && bundle exec rspec --tag integration
